#server.port=8888
#spring.application.name=config-server
#spring.cloud.config.server.git.uri=https://github.com/samim-git/sam-prj-config.git
#
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:samim-git/sam-prj-config.git
          skip-ssl-validation: true